# Generated by Django 6.0 on 2025-12-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_announcement_author_alter_room_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='admin',
        ),
    ]
